export interface CityOption {
  value: string
  he: string
  en: string
}

/** Major Israeli cities, alphabetical by Hebrew name. Add "Other" at end for tail cases. */
export const ISRAELI_CITIES: CityOption[] = [
  { value: 'eilat', he: 'אילת', en: 'Eilat' },
  { value: 'or-yehuda', he: 'אור יהודה', en: 'Or Yehuda' },
  { value: 'ofakim', he: 'אופקים', en: 'Ofakim' },
  { value: 'um-al-fahm', he: 'אום אל-פחם', en: 'Umm al-Fahm' },
  { value: 'ariel', he: 'אריאל', en: 'Ariel' },
  { value: 'ashdod', he: 'אשדוד', en: 'Ashdod' },
  { value: 'ashkelon', he: 'אשקלון', en: 'Ashkelon' },
  { value: 'be-er-sheva', he: 'באר שבע', en: 'Beer Sheva' },
  { value: 'bnei-brak', he: 'בני ברק', en: 'Bnei Brak' },
  { value: 'bat-yam', he: 'בת ים', en: 'Bat Yam' },
  { value: 'beit-shemesh', he: 'בית שמש', en: 'Beit Shemesh' },
  { value: 'beitar-illit', he: 'ביתר עילית', en: 'Beitar Illit' },
  { value: 'givatayim', he: 'גבעתיים', en: 'Givatayim' },
  { value: 'givat-shmuel', he: 'גבעת שמואל', en: 'Givat Shmuel' },
  { value: 'dimona', he: 'דימונה', en: 'Dimona' },
  { value: 'hadera', he: 'חדרה', en: 'Hadera' },
  { value: 'holon', he: 'חולון', en: 'Holon' },
  { value: 'haifa', he: 'חיפה', en: 'Haifa' },
  { value: 'tiberias', he: 'טבריה', en: 'Tiberias' },
  { value: 'yavne', he: 'יבנה', en: 'Yavne' },
  { value: 'yehud', he: 'יהוד-מונוסון', en: 'Yehud-Monosson' },
  { value: 'jerusalem', he: 'ירושלים', en: 'Jerusalem' },
  { value: 'kfar-saba', he: 'כפר סבא', en: 'Kfar Saba' },
  { value: 'modiin', he: 'מודיעין-מכבים-רעות', en: 'Modiin' },
  { value: 'modiin-illit', he: 'מודיעין עילית', en: 'Modiin Illit' },
  { value: 'maale-adumim', he: 'מעלה אדומים', en: 'Maale Adumim' },
  { value: 'nahariya', he: 'נהריה', en: 'Nahariya' },
  { value: 'nazareth', he: 'נצרת', en: 'Nazareth' },
  { value: 'nof-hagalil', he: 'נוף הגליל', en: 'Nof HaGalil' },
  { value: 'nes-tziona', he: 'נס ציונה', en: 'Nes Tziona' },
  { value: 'netanya', he: 'נתניה', en: 'Netanya' },
  { value: 'akko', he: 'עכו', en: 'Akko' },
  { value: 'petah-tikva', he: 'פתח תקווה', en: 'Petah Tikva' },
  { value: 'tzfat', he: 'צפת', en: 'Safed' },
  { value: 'kiryat-ata', he: 'קריית אתא', en: 'Kiryat Ata' },
  { value: 'kiryat-bialik', he: 'קריית ביאליק', en: 'Kiryat Bialik' },
  { value: 'kiryat-gat', he: 'קריית גת', en: 'Kiryat Gat' },
  { value: 'kiryat-shmona', he: 'קריית שמונה', en: 'Kiryat Shmona' },
  { value: 'rosh-haayin', he: 'ראש העין', en: 'Rosh HaAyin' },
  { value: 'rishon-letzion', he: 'ראשון לציון', en: 'Rishon LeZion' },
  { value: 'rehovot', he: 'רחובות', en: 'Rehovot' },
  { value: 'ramla', he: 'רמלה', en: 'Ramla' },
  { value: 'ramat-gan', he: 'רמת גן', en: 'Ramat Gan' },
  { value: 'ramat-hasharon', he: 'רמת השרון', en: 'Ramat HaSharon' },
  { value: 'raanana', he: 'רעננה', en: 'Raanana' },
  { value: 'tel-aviv', he: 'תל אביב יפו', en: 'Tel Aviv-Yafo' },
  { value: 'other', he: 'אחר', en: 'Other' },
]
